import { PrismaClient } from '@prisma/client';
import fs from 'fs';
import path from 'path';

const prisma = new PrismaClient();

async function generateCredentialsMD() {
  const teams = await prisma.team.findMany({
    include: {
      members: {
        include: {
          user: true,
        },
      },
    },
    orderBy: { registrationId: 'asc' },
  });

  const rows: {
    sNo: number;
    name: string;
    teamName: string;
    regId: string;
    role: string;
    email: string;
    password: string;
  }[] = [];

  let count = 1;

  for (const team of teams) {
    // Only team leaders have User ID and Password
    const leaderMember = team.members.find((m) => m.role === 'LEADER' || m.role === 'Team Leader');
    const leadEmail = team.leadEmail || leaderMember?.email;
    const leadName = team.leadName || leaderMember?.name;

    if (leadEmail && leadName) {
      rows.push({
        sNo: count++,
        name: leadName,
        teamName: team.name,
        regId: team.registrationId || team.teamCode || 'N/A',
        role: 'Team Leader',
        email: leadEmail,
        password: 'student123',
      });
    }
  }

  // Deduplicate by email
  const uniqueMap = new Map<string, typeof rows[0]>();
  rows.forEach((r) => {
    if (!uniqueMap.has(r.email.toLowerCase())) {
      uniqueMap.set(r.email.toLowerCase(), r);
    }
  });

  const uniqueRows = Array.from(uniqueMap.values());
  uniqueRows.forEach((r, idx) => {
    r.sNo = idx + 1;
  });

  let mdContent = `# SmartHorizon Hackathon 2026 - Team Leader Login Credentials

> **Notice:** Only Team Leaders have User IDs and login credentials to access the SmartHorizon Hackathon Operations Portal. Non-leader team members' details are preserved under their respective teams without individual login accounts.

---

### **Overview & Summary**
- **Total Registered Teams:** \`${teams.length}\`
- **Total Team Leader Accounts:** \`${uniqueRows.length}\`
- **Default Participant Password:** \`student123\`
- **Portal Login URL:** [http://localhost:8080/login](http://localhost:8080/login)

---

### **Team Leader Credentials Roster**

| S.No | Team Leader Name | Team Name | Reg ID | Role | Login Username (Email) | Password |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
`;

  uniqueRows.forEach((r) => {
    mdContent += `| ${r.sNo} | **${r.name}** | ${r.teamName} | \`${r.regId}\` | ${r.role} | \`${r.email}\` | \`${r.password}\` |\n`;
  });

  mdContent += `\n---\n*Generated by SmartHorizon System Administrator Desk on ${new Date().toLocaleString()}*\n`;

  const outputPath1 = path.join(__dirname, '../../Login credintials_particpants.md');
  const outputPath2 = path.join(__dirname, '../../Login_credentials_participants.md');

  fs.writeFileSync(outputPath1, mdContent, 'utf8');
  fs.writeFileSync(outputPath2, mdContent, 'utf8');

  console.log(`Generated ${uniqueRows.length} participant credentials into ${outputPath1}`);
}

generateCredentialsMD()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
